spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/accessibility}
    username: ${DB_USERNAME:accessibility}
    password: ${DB_PASSWORD:accessibility}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
