package ro.sluta.accessibility.domain;

public enum SnapshotErrorCode {
    INVALID_URL,
    DNS_RESOLUTION_FAILED,
    BLOCKED_ADDRESS,
    BLOCKED_REQUEST,
    REDIRECT_LIMIT_EXCEEDED,
    PAGE_LOAD_TIMEOUT,
    PAGE_UNAVAILABLE,
    MAIN_DOCUMENT_TOO_LARGE,
    RESOURCE_LIMIT_EXCEEDED,
    INVALID_INTERACTION_SCENARIO,
    INTERACTION_FAILED,
    SNAPSHOT_EXTRACTION_FAILED,
    ARTIFACT_WRITE_FAILED
}
